### ISSUE TITLE
Underground Outputs In a loop error

### ISSUE THREAD

**Issue by Nexela** [Nexela/PickerBeltTools#12]
```json
0eNqdVO2KwyAQfJf9baDaNmnzKkc5knYpQqLix9EQ8u6n6d0RUoM9f8kqzuzMDjtC2zlUmgsL9Qj8KoWB+mMEw++i6cKdHRRCDdxiDwRE04cKH0qjMYUTN9R3Lf1ZtNhZmAhwf/eAmk7kbRirG2GU1HYNwqYLARSWW47PxuZi+BSub1F7lhQWASWN/y5F6MJDFozAEA7PcuMar883FtpdgbO03ld4Gocnfw4I5YLEF7b9v6XElRwi2IcMJSkh0tkNJccc337E+NikCcoMggX+0qz0XKrciLEpgnbK92ZhzWaz5/zIrgZdvjEHusvM7Jorhk2zM7upZNM2yrITtRmoX9v8Bpu3Xr3YtQS+UJv5Q7Xf0ep4Olelz8s3QgPjkg==
```
510 attempt to get length of local input a nil value

**Comment by adrianvanderwal** [comment]
Using the above print, hover over any underground *exit* and the following error is logged:
```
Script @__stdlib__/stdlib/core.lua:50: __PickerBeltTools__/scripts/belt-highlight.lua:418: attempt to get length of local 'input' (a nil value)
```

**Comment by TheStaplergun** [comment]
Ya'll are both killin me. I don't have that version any more. Let me run it and find out where that line went to because you're both running different versions from what I have.

**Comment by Nexela** [comment]
I..... ammm....runnning.......the......latest......master :P  =NUB
Besides, why do you think I added the blueprint

**Comment by TheStaplergun** [comment]
![image](https://user-images.githubusercontent.com/27794580/59318294-8707e200-8c94-11e9-913c-dddc9e12c28b.png)

**Comment by TheStaplergun** [comment]
Why didn't this pcall my man.

**Comment by Nexela** [comment]
Uhmmmmmmm......... Did you break it? cause it did for me

**Comment by TheStaplergun** [comment]
Oh, right. Merged but didn't close my branch.

**Comment by Nexela** [comment]
Maybe you are not up to date with latest master :P

**Comment by Nexela** [comment]
Yeah I thought we were going off of master since most of the stuff is in

**Comment by TheStaplergun** [comment]
Yeah, I swapped branches and applied my fix there. Testing it now. It's a nil index error because of how I store data. Have to do a validation check now.
