### ISSUE TITLE
Option to disable belt path highlightning

### ISSUE THREAD

**Issue by dahcal** [Nexela/PickerBeltTools#2]
While the new feature of highlighting the belt path is useful, I would like a way to disable it.  Either by hotkey, alt-mode and/or settings page

**Comment by dahcal** [comment]
Small correction, while I found the hotkey in the settings, the toggle doesnt seem to be working

**Comment by Nexela** [comment]
Added in c36282c208d995fb56097e3fda6ccf276b026f29
