### ISSUE TITLE
Error when discarding concrete ghost from cursor

### ISSUE THREAD

**Issue by sparr** [Nexela/PickerBeltTools#22]
Put a concrete ghost on your cursor, such as from a quickbar shortcut with no concrete in your inventory. Press Q.

Error: `Script @__stdlib__/stdlib/core.lua:46: PickerBeltTools:__PickerBeltTools__/scripts/belt-brush.lua:40: attempt to index field 'place_result' (a nil value)`

**Comment by Nexela** [comment]
Thank you for the detailed report!
As this is not a major bug the release will probably wait until the next Factorio Version
