### ISSUE TITLE
Increase belt brush size doesn't work when bound to mouse-wheel

### ISSUE THREAD

**Issue by mgrubb** [Nexela/PickerBeltTools#3]
When `Larger tile building area` is bound to any combination of mouse wheel up or down (e.g. Control + Mouse Wheel up, etc) the belt brush does not respond by increasing or decreasing.

The stone brick path does respond to this keybinding, and if I bind that function to a keyboard key instead of mouse wheel the belt brush responds accordingly.

**Comment by Nexela** [comment]
Can not reproduce on .17.  using Shift + wheel up/down on worked correctly for increasing/decreasing the brush size.
